# Generated by Django 5.0.3 on 2024-10-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_prestacion_servicioprestacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_date',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='service',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='usuario',
        ),
    ]
